name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build
      env:
        VUE_APP_GA: ${{ secrets.GA }}
    - name: Deploy static site to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist
        remote: ${{ secrets.REMOTE_PATH }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
      env:
        CI: true
